/*
 * Tinkers Mechworks
 * Master build file
 * Based on TConstruct master build file
 * Authors: boni, Sunstrike, ProgWML6, fuj1n
 * Help from AbrarSyed
 */

buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
        maven { url = 'https://maven.parchmentmc.org' }
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '5.1.+', changing: true
        classpath 'org.parchmentmc:librarian:1.+'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.parchmentmc.librarian.forgegradle'
apply plugin: 'maven-publish'
apply from: 'https://raw.githubusercontent.com/SizableShrimp/Forge-Class-Remapper/main/classremapper.gradle'

repositories {
    maven {
        name 'DVS1 Maven FS'
        url 'https://dvs1.progwml6.com/files/maven'
    }
    maven {
        name 'forge'
        url 'https://maven.minecraftforge.net'
    }
    maven {
        name "Curse Maven"
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

group = "slimeknights.tmechworks"

version = "${minecraft_version}-${mod_version}"
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'parchment', version: "${mappings_version}-${minecraft_version}"

    runs {
        client {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES,REGISTRYDUMP,CORE,PULSAR'
            property 'forge.logging.console.level', 'debug'

            mods {
                tmechworks {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES,REGISTRYDUMP,CORE,PULSAR'
            property 'forge.logging.console.level', 'debug'

            mods {
                tmechworks {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'

            args '--mod', 'tmechworks', '--all', '--output', file('src/generated/resources/')

            mods {
                tmechworks {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
	minecraft 'net.minecraftforge:forge:' + minecraft_version + '-' + forge_version

    implementation fg.deobf("slimeknights.mantle:Mantle:${minecraft_version}-${mantle_version}")

	// compile against the JEI API
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    // at runtime, use the full JEI jar
    runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")

    implementation fg.deobf("curse.maven:jade-324717:${jade_version_id}")
}

sourceSets {
    main {
        resources {
            srcDirs 'src/generated/resources'
            //But exclude the cache of the generated data from what gets built
            exclude '.cache'
        }
    }
}

processResources {
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "MCversion", minecraft_version

    // expand version strings in mods.toml
    filesMatching('META-INF/mods.toml') {
        expand 'version': mod_version,
                'minecraft_version': minecraft_version,
                'forge_version': forge_version,
                'mantle_version': mantle_version,
                'loader_version': loader_version_toml
    }
}

jar {
    manifest {
        attributes([
			"Specification-Title"		: "Tinkers' Mechworks",
			"Specification-Vendor"		: "Slime Knights",
			"Specification-Version"		: "1", // We are version 1 of ourselves
			"Implementation-Title"		: project.name,
			"Implementation-Version"	: project.version,
			"Implementation-Vendor"		: "Slime Knights",
			"Implementation-Timestamp"	: new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
		])
    }
}

// Create deobf dev jars
task sourcesJar(type: Jar) {
    from sourceSets.main.allJava
    classifier = 'sources'
}

artifacts {
    archives sourcesJar
}