@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package slimeknights.tmechworks.api.disguisestate.facing;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;