@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package slimeknights.tmechworks.common.inventory.slots;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;