@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package slimeknights.tmechworks.integration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;