@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package slimeknights.tmechworks.integration.jade;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;