@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package slimeknights.tmechworks.common.entities;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;